name: githun_api_commits
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  dio: ^5.4.0
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  auto_route: ^7.8.4

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen: ^5.4.0
  flutter_gen_runner: ^5.4.0
  freezed: ^2.4.6
  lint: ^2.3.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.10
  custom_lint: ^0.5.11
  riverpod_lint: ^2.3.8
  auto_route_generator: ^7.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts
    - assets/images
    - assets/icons
    - assets/colors
    - assets/env

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
        - asset: assets/fonts/inter/Inter-Bold.ttf
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/inter/Inter-Light.ttf
        - asset: assets/fonts/inter/Inter-Medium.ttf
        - asset: assets/fonts/inter/Inter-Regular.ttf
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/Inter-Thin.ttf

flutter_gen:
  output: lib/app/gen/
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    outputs:
      class_name: AssetsToken
  fonts:
    enabled: true
    outputs:
      class_name: FontFamilyToken
  colors:
    enabled: true
    outputs:
      class_name: ColorsToken
    inputs:
      - assets/colors/colors.xml
